version: '3.9'
services:

    app:
        build: app
        volumes:
            - ./app:/code
        environment:
            FLASK_ENV: development

    nginx:
        container_name: nginx
        build: nginx
        ports:
            - 80:80
        depends_on:
           - app
           
           