version: '3.9'
services:

    app:
        build: .
        volumes:
            - .:/code
        environment:
            FLASK_ENV: development

    nginx:
        container_name: nginx
        build: nginx
        ports:
            - 8080:80
        depends_on:
           - app